name: SCVLE
favicon: null
layout_spectrum: 0.6598006789572537
typography_spectrum: 0.043812449323013425
title: Ideas that scale
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8507757128681988
  lightness: 0.2255253919865936
  saturation: 0.8355382613372058
  rhythmicContrast: 0.6614777473732829
purpose: []
