name: SCVLE
favicon: null
layout_spectrum: 0
typography_spectrum: 0.043812449323013425
title: Ideas that scale
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#dde7df'
    - '#e28e41'
    - '#3f3935'
    - '#73675d'
  brandStrength: 0.875
  lightness: 0.2255253919865936
  saturation: 0.8355382613372058
  rhythmicContrast: 0.6614777473732829
purpose: []
