name: SCVLE
favicon: null
layout_spectrum: 0.23539
typography_spectrum: 0.37603
title: Ideas that scale
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d2ddd9'
    - '#211926'
    - '#9e9791'
    - '#b5b4b0'
    - '#807b78'
  brandStrength: 0.875
  lightness: 0.25
  saturation: 0.8355382613372058
  rhythmicContrast: 0.75
purpose: []
